@startuml

left to right direction

package Kibana {
  node "Kibana-1"
  node "Kibana-2"
  node "Kibana-3"
}

package "ES Cluster 1" as esc1 {
  node "ES-1-1"
  node "ES-1-2"
  node "ES-1-3"
}

package "ES Cluster 2" as esc2 {
  node "ES-2-1"
  node "ES-2-2"
  node "ES-2-3"
}

esc1 --> Kibana
Kibana <-- esc2

@enduml
